server:
  port: 8081
  
spring:
  datasource:
    name: friends
  application:
    name: friends
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    
logging:
  level:
    org.springframework: error